apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
labels:
  - pairs:
      app: vprofile-app

    includeSelectors: true

secretGenerator:
  - name: database-root-credentials
    envs:
      - configs/database/.root.env

  - name: database-app-credentials
    envs:
      - configs/database/.app.env

  - name: broker-credentials
    envs:
      - configs/broker/.default.env

configMapGenerator:
  - name: db-init
    files:
      - configs/database/init.sql

resources:
  - database/statefulset.yaml
  - database/service.yaml
  - cache/deployment.yaml
  - cache/service.yaml
  - broker/deployment.yaml
  - broker/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
