apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: vprofile-app-
namespace: default
commonLabels:
  app: vprofile-app

secretGenerator:
  - name: database-root-credentials
    envs:
      - configs/database/.root.env

  - name: database-app-credentials
    envs:
      - configs/database/.app.env

configMapGenerator:
  - name: db-init
    files:
      - configs/database/init.sql

resources:
  - database/statefulset.yaml
  - database/headless-service.yaml
