apiVersion: v1
kind: Service
metadata:
  name: database

spec:
  clusterIP: None
  selector:
    app: vprofile-app
    tier: database

  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
